import { useEffect, useState } from 'react'
import { Check, KeyRound, Plus, ShieldCheck, UserRound, UsersRound } from 'lucide-react'
import { api } from './api.js'
import './Account.css'

const date = (value) => value ? new Date(value).toLocaleString('fr-FR') : 'Jamais'

export function ProfilePage({ user, onUpdate }) {
  const [name, setName] = useState(user.name), [message, setMessage] = useState('')
  const save = async (event) => { event.preventDefault(); const result = await api.updateProfile(name); onUpdate(result.user); setMessage('Profil mis à jour.') }
  return <><PageTitle eyebrow="COMPTE UTILISATEUR" title="Mon profil" description="Consultez et mettez à jour vos informations personnelles." /><section className="profile-page panel"><header><span><UserRound size={24} /></span><div><h2>{user.name}</h2><p>{user.owner ? 'FOUNDER' : user.role}</p></div><i>{user.status}</i></header><form onSubmit={save}><label><span>Nom complet</span><input value={name} onChange={(e) => setName(e.target.value)} required /></label><label><span>Email</span><input value={user.email} disabled /></label><div><span>Rôle</span><b>{user.role}</b></div><div><span>Date de création</span><b>{date(user.createdAt)}</b></div><div><span>Dernière connexion</span><b>{date(user.lastLogin)}</b></div><footer>{message && <span><Check size={14} />{message}</span>}<button className="primary">Enregistrer</button></footer></form></section></>
}

export function Administration() {
  const [users, setUsers] = useState([]), [open, setOpen] = useState(false), [notice, setNotice] = useState(''), [modal, setModal] = useState(null)
  const load = () => api.users().then(setUsers)
  useEffect(() => { load() }, [])
  const update = async (user, values) => { try { await api.updateUser(user.id, values); await load() } catch (error) { setNotice(error.message) } }
  return <><PageTitle eyebrow="FOUNDER" title="Administration" description="Gérez les comptes, rôles et accès au système." action={<button className="primary" onClick={() => setOpen(true)}><Plus size={17} />Créer un utilisateur</button>} /><section className="admin-users panel"><header><UsersRound size={19} /><div><h2>Gestion des utilisateurs</h2><p>{users.length} compte(s) enregistré(s)</p></div></header>{notice && <div className="admin-notice">{notice}</div>}<div className="admin-table"><table><thead><tr><th>Utilisateur</th><th>Rôle</th><th>Statut</th><th>Dernière connexion</th><th>Actions</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><b>{user.name}</b><small>{user.email}</small></td><td>{user.owner ? <span className="owner-badge">FOUNDER</span> : <select value={user.role} onChange={(e) => update(user, { role: e.target.value })}><option>RH</option><option>Superviseur</option><option>Directeur</option></select>}</td><td><span className={`account-status ${user.status !== 'Actif' ? 'disabled' : ''}`}>{user.status}</span></td><td>{date(user.lastLogin)}</td><td>{!user.owner && <div className="admin-actions"><button title={user.status === 'Actif'?'Désactiver':'Réactiver'} onClick={() => update(user, { status: user.status === 'Actif' ? 'Désactivé' : 'Actif' })}>{user.status === 'Actif' ? 'Désactiver' : 'Réactiver'}</button><button title="Réinitialiser le mot de passe" onClick={() => setModal({type:'reset',user})}><KeyRound size={14} /></button><button title="Supprimer" onClick={() => setModal({type:'delete',user})}>Supprimer</button></div>}</td></tr>)}</tbody></table></div></section>{open && <CreateUser close={() => setOpen(false)} created={(result) => { setOpen(false); setNotice('Compte créé avec succès. Définissez un mot de passe temporaire pour le nouvel utilisateur.'); load() }} />}{modal?.type==='reset'&&<ResetUser user={modal.user} close={()=>setModal(null)} done={(message)=>{setModal(null);setNotice(message)}}/>}{modal?.type==='delete'&&<DeleteUser user={modal.user} close={()=>setModal(null)} done={(message)=>{setModal(null);setNotice(message);load()}}/>}</>
}

function CreateUser({ close, created }) {
  const [values, setValues] = useState({ name: '', email: '', role: 'RH', temporaryPassword: '' }), [error, setError] = useState('')
  const submit = async (event) => { event.preventDefault(); try { created(await api.createUser(values)) } catch (reason) { setError(reason.message) } }
  return <div className="modal-layer"><button className="backdrop" onClick={close} /><form className="create-user" onSubmit={submit}><header><span><ShieldCheck size={22} /></span><div><h2>Créer un utilisateur</h2><p>Le rôle Founder ne peut pas être attribué ici.</p></div></header><label><span>Nom complet</span><input value={values.name} onChange={(e) => setValues({ ...values, name: e.target.value })} required /></label><label><span>Email</span><input type="email" value={values.email} onChange={(e) => setValues({ ...values, email: e.target.value })} required /></label><label><span>Rôle</span><select value={values.role} onChange={(e) => setValues({ ...values, role: e.target.value })}><option>RH</option><option>Superviseur</option><option>Directeur</option></select></label><label><span>Mot de passe temporaire (12 caractères minimum)</span><input type="password" minLength="12" value={values.temporaryPassword} onChange={(e)=>setValues({...values,temporaryPassword:e.target.value})} required /></label>{error && <p className="admin-error">{error}</p>}<footer><button type="button" className="secondary" onClick={close}>Annuler</button><button className="primary">Créer le compte</button></footer></form></div>
}

function ResetUser({user,close,done}){const [password,setPassword]=useState(''),[error,setError]=useState('');const submit=async(e)=>{e.preventDefault();try{await api.resetPassword(user.id,password);done('Réinitialisation effectuée. Le changement de mot de passe sera demandé à la prochaine connexion.')}catch(reason){setError(reason.message)}};return <div className="modal-layer"><button className="backdrop" onClick={close}/><form className="create-user" onSubmit={submit}><header><span><KeyRound size={22}/></span><div><h2>Réinitialiser le mot de passe</h2><p>{user.name} · {user.email}</p></div></header><label><span>Mot de passe temporaire (12 caractères minimum)</span><input type="password" minLength="12" value={password} onChange={(e)=>setPassword(e.target.value)} required/></label>{error&&<p className="admin-error">{error}</p>}<footer><button type="button" className="secondary" onClick={close}>Annuler</button><button className="primary">Réinitialiser</button></footer></form></div>}
function DeleteUser({user,close,done}){const submit=async()=>{try{await api.deleteUser(user.id);done('Le compte utilisateur a été supprimé.')}catch(reason){done(reason.message)}};return <div className="modal-layer"><button className="backdrop" onClick={close}/><div className="create-user delete-user"><header><span><ShieldCheck size={22}/></span><div><h2>Supprimer cet utilisateur ?</h2><p>Cette action supprimera définitivement le compte utilisateur de {user.name}.</p></div></header><footer><button className="secondary" onClick={close}>Annuler</button><button className="reset-confirm" onClick={submit}>Supprimer définitivement</button></footer></div></div>}

function PageTitle({ eyebrow, title, description, action }) { return <div className="intro"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div> }
