import { useEffect, useMemo, useRef, useState } from 'react'
import { Activity, BarChart3, Bell, BriefcaseBusiness, Building2, CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, ChevronsUpDown, CircleDollarSign, Download, FileBarChart, Filter, Gauge, Home, LogOut, MapPin, Menu, Moon, Pencil, Plus, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, Sun, Trash2, UserRound, UsersRound, WalletCards, X } from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import logo from '../../TOTAL WORK LOGO.jpg'
import { axis, categorical, cursor, grid, sequential, sliceGap } from './charts.js'
import ExcelImport, { ImportHistory } from './ExcelImport.jsx'
import { assertUniqueMatricules, normalizeMatricule, recordKey } from './import-utils.js'
import DataReset from './DataReset.jsx'
import { AuthLoading, ForcePasswordChange, Login } from './Auth.jsx'
import { Administration, ProfilePage } from './Account.jsx'
import { api } from './api.js'
import SystemHealth from './SystemHealth.jsx'
import { UNSET, applyFilters, compact, csvDocument, download, groupRows, grouped, initials, money, number, payDay, rate, sum, unique } from './metrics.js'
import { storage, useAnimated, useDismiss } from './hooks.js'
import { Empty, ErrorBoundary, Intro, Overlay } from './shared.jsx'

const NAV = [
  ['overview', 'Vue d’ensemble', Home], ['housing', 'Logements', Building2],
  ['payments', 'Paiements', WalletCards], ['analytics', 'Analyse & Statistiques', BarChart3],
  ['companies', 'Entreprises', BriefcaseBusiness], ['locations', 'Localisations', MapPin],
  ['reports', 'Rapports', FileBarChart], ['settings', 'Paramètres', Settings],
]
const TITLES = { ...Object.fromEntries(NAV.map(([id, label]) => [id, label])), profile: 'Mon profil', administration: 'Administration' }
const EMPTY_FILTERS = { location: '', company: '', matricule: '', chantier: '', responsible: '', from: 1, to: 31 }
const EMPTY_FORM = { matricule: '', people: '', capacity: '', payDay: '', price: '', startMonth: '', responsible: '', company: '', chantier: '', location: '', remark: '' }

/* The persisted theme choice. Read once at startup and written on every
   change, so the key is stated here rather than at both call sites. */
const THEME_KEY = 'tw-theme'

export default function App() {
  const [loading, setLoading] = useState(true)
  const [auth, setAuth] = useState(null)
  const [page, setPage] = useState('overview')
  const [collapsed, setCollapsed] = useState(false)
  const [mobileNav, setMobileNav] = useState(false)
  const [theme, setTheme] = useState(() => storage.get(THEME_KEY, 'light'))
  const [data, setData] = useState([])
  const [filters, setFilters] = useState(EMPTY_FILTERS)
  const [detail, setDetail] = useState(null)
  const [form, setForm] = useState(null)
  const [toast, setToast] = useState('')
  const [history, setHistory] = useState([])
  const currentUser = auth?.user
  const permission = (name) => auth?.permissions?.includes(name)
  const loadBusinessData = async () => { const [records, imports] = await Promise.all([api.housing(), api.history()]); setData(records); setHistory(imports) }
  useEffect(() => { api.session().then(async (session) => { setAuth(session); if (!session.user.passwordResetRequired) await loadBusinessData() }).catch(() => setAuth(null)).finally(() => setLoading(false)) }, [])
  useEffect(() => { const icon = document.querySelector('link[rel="icon"]') || document.createElement('link'); icon.rel = 'icon'; icon.type = 'image/jpeg'; icon.href = logo; document.head.appendChild(icon) }, [])
  useEffect(() => { document.documentElement.dataset.theme = theme; storage.set(THEME_KEY, theme) }, [theme])
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 2600); return () => clearTimeout(timer) }, [toast])
  const filtered = useMemo(() => applyFilters(data, filters), [data, filters])
  const save = async (record, original) => { if (!permission('housing:write')) throw new Error('Accès refusé'); const normalizedRecord = { ...record, matricule: normalizeMatricule(record.matricule) }; const next = original ? data.map((item) => recordKey(item) === original ? normalizedRecord : item) : [...data, normalizedRecord]; assertUniqueMatricules(next); if (original) await api.updateHousing(original, normalizedRecord); else await api.createHousing(normalizedRecord); setData(next); setForm(null); setToast(original ? 'Le logement a été mis à jour.' : 'Le logement a été ajouté.') }
  const remove = async (record) => { if (!permission('housing:write')) return setToast('Accès refusé.'); if (!confirm(`Supprimer définitivement le logement ${record.matricule} ?`)) return; await api.deleteHousing(recordKey(record)); setData((items) => items.filter((item) => recordKey(item) !== recordKey(record))); setDetail(null); setToast('Le logement a été supprimé.') }
  const resetBusinessData = async () => {
    if (!permission('reset')) throw new Error('Accès refusé')
    await api.resetHousing()
    setData([]); setHistory([]); setFilters(EMPTY_FILTERS); setDetail(null); setForm(null)
    setToast('Données réinitialisées avec succès. Le système est prêt à recevoir un nouveau fichier Excel.')
  }
  if (loading) return <AuthLoading />
  if (!auth) return <Login theme={theme} setTheme={setTheme} onLogin={async (session) => { setAuth(session); if (!session.user.passwordResetRequired) await loadBusinessData() }} />
  if (auth.user.passwordResetRequired) return <ForcePasswordChange onComplete={async (user)=>{setAuth((value)=>({...value,user}));await loadBusinessData()}} />
  const navigable = ['overview', 'housing', 'payments', 'analytics'].includes(page)
  return <div className={`app ${collapsed ? 'collapsed' : ''}`}>
    <Sidebar {...{ page, setPage, collapsed, setCollapsed, mobileNav, setMobileNav }} user={currentUser} permissions={auth.permissions} />
    <main><Topbar {...{ page, setMobileNav, theme, setTheme }} user={currentUser} canWrite={permission('housing:write')} onAdd={() => setForm({ mode: 'add', data: EMPTY_FORM })} onProfile={() => setPage('profile')} onAdmin={() => setPage('administration')} onLogout={async () => { await api.logout(); setAuth(null); setData([]) }} />
      <div className="page" key={page}>{navigable && <Filters data={data} filters={filters} setFilters={setFilters} />}
        {/* `.page` above is keyed on the page, so navigating away from a view
            that threw remounts this boundary and clears the error instead of
            stranding the user on it. The fragment keeps this a single child and
            adds no element, so `.page` still lays out the panels itself. */}
        <ErrorBoundary><>
          {page === 'overview' && <Overview data={filtered} filters={filters} onPage={setPage} onDetail={setDetail} />}
          {page === 'housing' && <Housing data={filtered} total={data.length} onDetail={setDetail} onAdd={permission('housing:write') ? () => setForm({ mode: 'add', data: EMPTY_FORM }) : null} />}
          {page === 'payments' && <Payments data={filtered} filters={filters} setFilters={setFilters} />}
          {page === 'analytics' && <Analytics data={filtered} />}
          {page === 'companies' && <Directory kind="company" data={data} onSelect={(value) => { setFilters({ ...EMPTY_FILTERS, company: value }); setPage('housing') }} />}
          {page === 'locations' && <Directory kind="location" data={data} onSelect={(value) => { setFilters({ ...EMPTY_FILTERS, location: value }); setPage('housing') }} />}
          {page === 'reports' && <Reports data={filtered} />}
          {page === 'settings' && permission('settings') && <SettingsPage theme={theme} setTheme={setTheme} data={data} history={history} currentUser={currentUser} onImport={async (next, result) => { const normalized = next.map((item) => ({ ...item, matricule: normalizeMatricule(item.matricule) })); assertUniqueMatricules(normalized); const payload = result.mode === 'replace' ? normalized : result.mode === 'add' ? normalized.filter((item) => !data.some((row) => recordKey(row) === recordKey(item))) : normalized; await api.syncHousing(payload, result.mode, result.file); await loadBusinessData(); setToast('Importation terminée avec succès.') }} onReset={resetBusinessData} />}
          {page === 'profile' && <ProfilePage user={currentUser} onUpdate={(user) => setAuth((value) => ({ ...value, user }))} />}
          {page === 'administration' && permission('users:manage') && <Administration />}
        </></ErrorBoundary>
      </div>
    </main>
    {detail && <Drawer record={detail} close={() => setDetail(null)} edit={permission('housing:write') ? () => { setForm({ mode: 'edit', data: detail }); setDetail(null) } : null} remove={permission('housing:write') ? () => remove(detail) : null} />}
    {form && <Form initial={form.data} mode={form.mode} records={data} close={() => setForm(null)} save={save} />}
    {toast && <div className="toast"><Check size={16} />{toast}</div>}
  </div>
}

function Sidebar({ page, setPage, collapsed, setCollapsed, mobileNav, setMobileNav, user, permissions }) {
  const allowed = NAV.filter(([id]) => id !== 'settings' || permissions.includes('settings'))
  const adminItems = [...allowed.slice(4), ...(permissions.includes('users:manage') ? [['administration', 'Administration', ShieldCheck]] : [])]
  return <>{mobileNav && <button className="backdrop nav-backdrop" aria-label="Fermer" onClick={() => setMobileNav(false)} />}<aside className={`sidebar ${mobileNav ? 'open' : ''}`}><div className="brand"><img src={logo} alt="TOTAL WORK" /><div><b>TOTAL WORK</b><span>Gestion des logements</span></div></div><nav><small>ESPACE DE GESTION</small>{allowed.slice(0, 4).map(([id, label, Icon]) => <Nav key={id} {...{ id, label, Icon, page, setPage, setMobileNav }} />)}<small>ADMINISTRATION</small>{adminItems.map(([id, label, Icon]) => <Nav key={id} {...{ id, label, Icon, page, setPage, setMobileNav }} />)}</nav><footer><Activity size={18} /><div><b>{user.owner ? 'FOUNDER' : user.role}</b><span>Session sécurisée</span></div></footer><button className="collapse" onClick={() => setCollapsed(!collapsed)} title={collapsed ? 'Déployer' : 'Réduire'}><ChevronLeft size={17} /></button></aside></>
}
function Nav({ id, label, Icon, page, setPage, setMobileNav }) { return <button data-nav-id={id} className={page === id ? 'active' : ''} title={label} onClick={() => { setPage(id); setMobileNav(false) }}><Icon size={18} /><span>{label}</span></button> }
function Topbar({ page, setMobileNav, theme, setTheme, onAdd, user, canWrite, onProfile, onAdmin, onLogout }) { const [open, setOpen] = useState(false), actions = useRef(null); useDismiss(actions, () => setOpen(false), open); return <header className="topbar"><div className="top-title"><button className="icon mobile-menu" onClick={() => setMobileNav(true)}><Menu size={19} /></button><section><span>Gestion des logements</span><b>{TITLES[page]}</b></section></div><div className="top-actions" ref={actions}><button className="icon" title="Changer le thème" onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')}>{theme === 'light' ? <Moon size={18} /> : <Sun size={18} />}</button><button className="icon bell"><Bell size={18} /><i /></button>{canWrite && <button className="primary top-add" title="Ajouter un logement" onClick={() => { setOpen(false); onAdd() }}><Plus size={17} />Ajouter un logement</button>}<button className="profile" onClick={() => setOpen(!open)}><span>{initials(user.name)}</span><section><b>{user.name}</b><small>{user.owner ? 'FOUNDER' : user.role}</small></section><ChevronDown size={14} /></button>{open && <div className="profile-menu"><button onClick={() => { onProfile(); setOpen(false) }}><UserRound size={15} />Mon profil</button>{user.owner && <button onClick={() => { onAdmin(); setOpen(false) }}><ShieldCheck size={15} />Administration</button>}<button onClick={onLogout}><LogOut size={15} />Déconnexion</button></div>}</div></header> }

function Filters({ data, filters, setFilters }) {
  const set = (key, value) => setFilters((current) => ({ ...current, [key]: value }))
  return <section className="filters"><header><div><Filter size={17} /><b>Filtres globaux</b><span>{data.length} enregistrements disponibles</span></div><button onClick={() => setFilters(EMPTY_FILTERS)}><RefreshCw size={14} />Réinitialiser</button></header><div className="filter-grid"><label><span>Rechercher par matricule</span><div className="input-icon"><Search size={15} /><input value={filters.matricule} onChange={(e) => set('matricule', e.target.value)} placeholder="Ex. TOT-A125" list="matricules" /><datalist id="matricules">{unique(data, 'matricule').map((v) => <option key={v}>{v}</option>)}</datalist></div></label><Select label="Localisation" value={filters.location} options={unique(data, 'location')} change={(v) => set('location', v)} /><Select label="Entreprise" value={filters.company} options={unique(data, 'company')} change={(v) => set('company', v)} /><Select label="Chantier" value={filters.chantier} options={unique(data, 'chantier')} change={(v) => set('chantier', v)} /><Select label="Responsable" value={filters.responsible} options={unique(data, 'responsible')} change={(v) => set('responsible', v)} /><label><span>Période de paiement</span><div className="range"><input type="number" min="1" max="31" value={filters.from} onChange={(e) => set('from', Math.min(payDay(e.target.value, filters.from), filters.to))} /><i>à</i><input type="number" min="1" max="31" value={filters.to} onChange={(e) => set('to', Math.max(payDay(e.target.value, filters.to), filters.from))} /></div></label></div></section>
}
function Select({ label, value, options, change }) { return <label><span>{label}</span><div className="select"><select value={value} onChange={(e) => change(e.target.value)}><option value="">Toutes</option>{options.map((option) => <option key={option}>{option}</option>)}</select><ChevronDown size={14} /></div></label> }

function Overview({ data, filters, onPage, onDetail }) {
  const locations = grouped(data, 'location', 'count').slice(0, 7)
  /* Ranked single measure → sequential ramp, and the data is already sorted
     desc, so the darkest green lands on the tallest bar. */
  const ramp = sequential(locations.length)
  const payments = grouped(data, 'payDay').sort((a, b) => a.name - b.name).map((v) => ({ ...v, name: String(v.name).padStart(2, '0') }))
  return <><Intro eyebrow="TOTAL WORK · OPÉRATIONS D’HÉBERGEMENT" title="Pilotage du parc de logements" description="Une vision consolidée de l’occupation, des capacités et des engagements financiers." action={<div className="operational"><i />Système opérationnel</div>} /><Kpis data={data} />{data.length ? <><div className="dash-grid"><Chart title="Répartition par localisation" subtitle="Nombre de logements actifs"><ResponsiveContainer width="100%" height={265}><BarChart data={locations} margin={{ left: -25, right: 8 }}><CartesianGrid {...grid} /><XAxis dataKey="name" {...axis} tickFormatter={(v) => v.length > 10 ? `${v.slice(0, 9)}…` : v} /><YAxis {...axis} allowDecimals={false} /><Tooltip content={<Tip suffix=" logement(s)" />} cursor={cursor} /><Bar dataKey="amount" radius={[4, 4, 0, 0]} maxBarSize={36}>{ramp.map((fill, i) => <Cell key={i} fill={fill} />)}</Bar></BarChart></ResponsiveContainer></Chart><Occupation data={data} /></div><div className="dash-grid lower"><Chart title="Échéancier de paiement" subtitle={`Montants du jour ${String(filters.from).padStart(2, '0')} au ${String(filters.to).padStart(2, '0')}`}><ResponsiveContainer width="100%" height={235}><AreaChart data={payments} margin={{ left: -8, right: 10 }}><defs><linearGradient id="amount" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--brand)" stopOpacity=".22" /><stop offset="1" stopColor="var(--brand)" stopOpacity="0" /></linearGradient></defs><CartesianGrid {...grid} /><XAxis dataKey="name" {...axis} /><YAxis {...axis} tickFormatter={(v) => compact.format(v)} /><Tooltip content={<Tip monetary />} /><Area type="monotone" dataKey="amount" stroke="var(--brand)" strokeWidth={2.5} fill="url(#amount)" /></AreaChart></ResponsiveContainer></Chart><Recent data={data.slice(0, 5)} onDetail={onDetail} onPage={onPage} /></div></> : <Empty />}</>
}
/* No per-card tone. Six differently-coloured icon wells above six unrelated
   numbers is the "pile of widgets" look; the wells are one brand family and
   the numerals carry the difference. The old tone strings ('red', 'gold', …)
   had no matching rule left and are gone rather than left dangling. */
function Kpis({ data }) { const people = sum(data, 'people'), capacity = sum(data, 'capacity'); const values = [['Logements', data.length, 'unités dans le périmètre', Building2, ''], ['Personnes hébergées', people, `${Math.max(capacity - people, 0)} places disponibles`, UsersRound, ''], ['Capacité totale', capacity, 'places déclarées', Gauge, ''], ['Taux d’occupation', rate(data), 'utilisation de la capacité', Activity, '%'], ['Montant total', sum(data, 'price'), 'engagement mensuel', CircleDollarSign, ' MAD'], ['Entreprises', unique(data, 'company').length, `${unique(data, 'location').length} localisations`, BriefcaseBusiness, '']]; return <div className="kpis">{values.map(([label, value, sub, Icon, suffix]) => <Kpi key={label} {...{ label, value, sub, Icon, suffix }} />)}</div> }
function Kpi({ label, value, sub, Icon, suffix }) { const shown = useAnimated(value), amount = label === 'Montant total'; return <article className={amount ? 'amount-kpi' : ''}><span className="kpi-icon"><Icon size={19} /></span><section><small>{label}</small><b className="kpi-value" title={amount ? `${number.format(Math.round(shown))}${suffix}` : undefined}>{number.format(Math.round(shown))}{suffix}</b><i>{sub}</i></section></article> }
function Chart({ title, subtitle, legend, children }) { return <section className="panel chart"><header><div><h2>{title}</h2><p>{subtitle}</p></div>{legend ? <ul className="series-key">{legend.map(([name, color]) => <li key={name}><i style={{ background: color }} />{name}</li>)}</ul> : null}</header>{children}</section> }
/* One row per series. The single-payload shape is kept for the many charts
   that have one series, but a grouped chart used to render only payload[0]
   and silently drop the rest — the swatch is what ties each row to its bar. */
function Tip({ active, payload, label, monetary, suffix = '' }) { if (!active || !payload?.length) return null; const show = (v) => monetary ? money.format(v) : `${number.format(v)}${suffix}`; return <div className="tip"><span>{label || payload[0].payload.name}</span>{payload.length > 1 ? payload.map((s) => <em key={s.name ?? s.dataKey}><i style={{ background: s.color || s.fill }} />{s.name}<b>{show(s.value)}</b></em>) : <b>{show(payload[0].value)}</b>}</div> }
/* Part-of-whole gauge, not a category breakdown — the two slices mean
   "filled" and "empty", so they stay on the semantic --brand / --chart-muted
   pair. Running the categorical palette here would imply the empty places are
   just another category. */
function Occupation({ data }) { const people = sum(data, 'people'), capacity = sum(data, 'capacity'), occupancy = rate(data), pie = [{ value: people }, { value: Math.max(capacity - people, 0) }]; return <section className="panel occupation"><header><div><h2>Occupation du parc</h2><p>Utilisation de la capacité totale</p></div><span>Temps réel</span></header><div className="donut"><ResponsiveContainer width="100%" height={175}><PieChart><Pie data={pie} dataKey="value" innerRadius={57} outerRadius={74} startAngle={90} endAngle={-270} stroke="none"><Cell fill="var(--brand)" /><Cell fill="var(--chart-muted)" /></Pie></PieChart></ResponsiveContainer><section><b>{occupancy}%</b><span>occupé</span></section></div><footer><div><i className="occupied" />Places occupées <b>{people}</b></div><div><i />Places disponibles <b>{Math.max(capacity - people, 0)}</b></div></footer></section> }
function Recent({ data, onDetail, onPage }) { return <section className="panel recent"><header><div><h2>Aperçu des logements</h2><p>Premiers résultats du périmètre filtré</p></div><button onClick={() => onPage('housing')}>Tout afficher <ChevronRight size={14} /></button></header>{data.map((item) => <button className="recent-row" key={recordKey(item)} onClick={() => onDetail(item)}><span className="unit"><Building2 size={16} /></span><section><b>{item.matricule}</b><small>{item.location} · {item.company}</small></section><Status item={item} /><ChevronRight size={15} /></button>)}</section> }
function Status({ item }) { const invalid = item.people == null || item.capacity == null; return <span className={`status ${!invalid && item.people >= item.capacity ? 'full' : ''} ${invalid ? 'invalid' : ''}`}>{invalid ? 'À vérifier' : item.people >= item.capacity ? 'Complet' : 'Disponible'}</span> }

function Housing({ data, total, onDetail, onAdd }) {
  const [query, setQuery] = useState(''), [sort, setSort] = useState({ key: 'matricule', direction: 1 }), [current, setCurrent] = useState(1)
  const perPage = 12
  const rows = useMemo(() => data.filter((item) => Object.values(item).some((value) => String(value ?? '').toLowerCase().includes(query.toLowerCase()))).sort((a, b) => String(a[sort.key] ?? '').localeCompare(String(b[sort.key] ?? ''), 'fr', { numeric: true }) * sort.direction), [data, query, sort])
  const pages = Math.max(1, Math.ceil(rows.length / perPage))
  useEffect(() => setCurrent(1), [query, data])
  const sortBy = (key) => setSort((value) => ({ key, direction: value.key === key ? -value.direction : 1 }))
  const columns = [['matricule', 'Matricule'], ['location', 'Localisation'], ['company', 'Entreprise'], ['chantier', 'Chantier'], ['people', 'Personnes'], ['capacity', 'Capacité'], ['payDay', 'Paiement'], ['price', 'Montant']]
  return <><Intro eyebrow="PARC IMMOBILIER" title="Gestion des logements" description={`${rows.length} logement(s) affiché(s) sur ${total} au total.`} action={onAdd ? <button className="primary" onClick={onAdd}><Plus size={17} />Ajouter un logement</button> : null} /><section className="panel table-panel"><header className="table-tools"><div className="input-icon"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Rechercher dans les résultats..." /></div><span><SlidersHorizontal size={15} />{rows.length} résultat(s)</span></header>{rows.length ? <><div className="table-scroll"><table><thead><tr>{columns.map(([key, label]) => <th key={key}><button onClick={() => sortBy(key)}>{label}<ChevronsUpDown size={12} /></button></th>)}<th>État</th><th /></tr></thead><tbody>{rows.slice((current - 1) * perPage, current * perPage).map((item) => <tr key={item.matricule} onClick={() => onDetail(item)}><td><b>{item.matricule}</b></td><td><MapPin size={13} />{item.location || 'Non renseignée'}</td><td><span className="company-badge">{initials(item.company || 'NR')}</span>{item.company || 'Non renseignée'}</td><td>{item.chantier || '—'}</td><td>{item.people ?? '—'}</td><td>{item.capacity ?? '—'}</td><td>Le {String(item.payDay).padStart(2, '0')}</td><td><b>{money.format(item.price || 0)}</b></td><td><Status item={item} /></td><td><ChevronRight size={15} /></td></tr>)}</tbody></table></div><Pagination current={current} pages={pages} set={setCurrent} /></> : <Empty />}</section></>
}
function Pagination({ current, pages, set }) { return <footer className="pagination"><span>Page {current} sur {pages}</span><div><button disabled={current === 1} onClick={() => set(current - 1)}><ChevronLeft size={16} /></button>{Array.from({ length: Math.min(pages, 5) }, (_, index) => <button className={current === index + 1 ? 'active' : ''} key={index} onClick={() => set(index + 1)}>{index + 1}</button>)}<button disabled={current === pages} onClick={() => set(current + 1)}><ChevronRight size={16} /></button></div></footer> }

function Payments({ data, filters, setFilters }) {
  const total = sum(data, 'price'), values = data.map((item) => item.price).filter(Number.isFinite), daily = grouped(data, 'payDay').sort((a, b) => a.name - b.name).map((v) => ({ ...v, name: `Jour ${String(v.name).padStart(2, '0')}` })), companies = grouped(data, 'company').slice(0, 7)
  /* Same encoding as the Overview location bars: one measure, already ranked. */
  const ramp = sequential(companies.length)
  return <><Intro eyebrow="ANALYSE FINANCIÈRE" title="Paiements" description="Analyse inclusive des montants selon les jours de paiement sélectionnés." /><section className="payment-hero"><div><span><CalendarDays size={18} />Période analysée</span><b>Du jour {String(filters.from).padStart(2, '0')} au jour {String(filters.to).padStart(2, '0')}</b><small>Les deux bornes sont incluses dans le calcul.</small></div><section><label><span>Du jour</span><input type="number" min="1" max="31" value={filters.from} onChange={(e) => setFilters((f) => ({ ...f, from: Math.min(payDay(e.target.value, f.from), f.to) }))} /></label><i /><label><span>Au jour</span><input type="number" min="1" max="31" value={filters.to} onChange={(e) => setFilters((f) => ({ ...f, to: Math.max(payDay(e.target.value, f.to), f.from) }))} /></label></section><div><span>Montant de la période</span><b>{money.format(total)}</b><small>{data.length} échéance(s) concernée(s)</small></div></section><div className="payment-kpis">{[['Nombre d’enregistrements', number.format(data.length), FileBarChart], ['Paiement moyen', money.format(data.length ? total / data.length : 0), Gauge], ['Paiement minimum', money.format(values.length ? Math.min(...values) : 0), ChevronDown], ['Paiement maximum', money.format(values.length ? Math.max(...values) : 0), Activity]].map(([label, value, Icon]) => <article key={label}><Icon size={18} /><span>{label}</span><b>{value}</b></article>)}</div>{data.length ? <div className="dash-grid"><Chart title="Montant par date de paiement" subtitle="Évolution des engagements sur la période"><ResponsiveContainer width="100%" height={295}><LineChart data={daily} margin={{ left: 0, right: 12 }}><CartesianGrid {...grid} /><XAxis dataKey="name" {...axis} /><YAxis {...axis} tickFormatter={(v) => compact.format(v)} /><Tooltip content={<Tip monetary />} /><Line type="monotone" dataKey="amount" stroke="var(--brand)" strokeWidth={3} dot={{ fill: 'var(--surface)', stroke: 'var(--brand)', strokeWidth: 2, r: 4 }} activeDot={{ fill: 'var(--brand)', stroke: 'var(--surface)', strokeWidth: 2, r: 6 }} /></LineChart></ResponsiveContainer></Chart><Chart title="Montant par entreprise" subtitle="Répartition des dépenses filtrées"><ResponsiveContainer width="100%" height={295}><BarChart data={companies} layout="vertical" margin={{ left: 4, right: 25 }}><CartesianGrid horizontal={false} stroke="var(--grid)" /><XAxis type="number" {...axis} tickFormatter={(v) => compact.format(v)} /><YAxis dataKey="name" type="category" {...axis} width={80} /><Tooltip content={<Tip monetary />} cursor={cursor} /><Bar dataKey="amount" radius={[0, 4, 4, 0]} maxBarSize={24}>{ramp.map((fill, i) => <Cell key={i} fill={fill} />)}</Bar></BarChart></ResponsiveContainer></Chart></div> : <Empty />}</>
}

function Analytics({ data }) {
  const locations = grouped(data, 'location', 'count').slice(0, 8), companies = grouped(data, 'company', 'count'), occupancy = groupRows(data, 'location', 'people').map(({ name, amount, rows }) => ({ name, amount, capacity: sum(rows, 'capacity') })).slice(0, 8), starts = grouped(data.filter((item) => item.startMonth), 'startMonth', 'count').sort((a, b) => a.name.localeCompare(b.name))
  /* Location bars are one ranked measure → ramp. The company pie is unordered
     entities and is NOT capped, so it is the one place cardinality is truly
     unbounded — categorical() derives past eight instead of wrapping. */
  const ramp = sequential(locations.length), slices = categorical(companies.length)
  return <><Intro eyebrow="AIDE À LA DÉCISION" title="Analyse & statistiques" description="Indicateurs opérationnels utiles pour piloter le parc et anticiper les besoins." />{data.length ? <div className="analytics"><Chart title="Logements par localisation" subtitle="Concentration géographique du parc"><ResponsiveContainer width="100%" height={295}><BarChart data={locations} margin={{ left: -25 }}><CartesianGrid {...grid} /><XAxis dataKey="name" {...axis} tickFormatter={(v) => v.length > 9 ? `${v.slice(0, 8)}…` : v} /><YAxis {...axis} allowDecimals={false} /><Tooltip content={<Tip suffix=" logement(s)" />} cursor={cursor} /><Bar dataKey="amount" radius={[4, 4, 0, 0]} maxBarSize={44}>{ramp.map((fill, i) => <Cell key={i} fill={fill} />)}</Bar></BarChart></ResponsiveContainer></Chart><Chart title="Répartition par entreprise" subtitle={`Part de chaque entité dans le parc · ${companies.length} entreprise(s)`}><div className="donut-layout"><ResponsiveContainer width="58%" height={255}><PieChart><Pie data={companies} dataKey="amount" nameKey="name" innerRadius={62} outerRadius={89} {...sliceGap(companies.length)}>{slices.map((fill, i) => <Cell key={i} fill={fill} />)}</Pie><Tooltip content={<Tip suffix=" logement(s)" />} /></PieChart></ResponsiveContainer><div className="legend">{companies.map((item, i) => <div key={item.name}><i style={{ background: slices[i] }} /><span title={item.name}>{item.name}</span><b>{item.amount}</b></div>)}</div></div></Chart><Chart title="Occupation vs capacité" subtitle="Écart de capacité par localisation" legend={[['Personnes', 'var(--brand)'], ['Capacité', 'var(--chart-muted)']]}><ResponsiveContainer width="100%" height={305}><BarChart data={occupancy} margin={{ left: -15 }}><CartesianGrid {...grid} /><XAxis dataKey="name" {...axis} tickFormatter={(v) => v.length > 9 ? `${v.slice(0, 8)}…` : v} /><YAxis {...axis} /><Tooltip content={<Tip suffix=" place(s)" />} cursor={cursor} /><Bar name="Personnes" dataKey="amount" fill="var(--brand)" radius={[3, 3, 0, 0]} /><Bar name="Capacité" dataKey="capacity" fill="var(--chart-muted)" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer></Chart><Chart title="Démarrage des logements" subtitle="Enregistrements disposant d’un mois de début"><ResponsiveContainer width="100%" height={305}><AreaChart data={starts} margin={{ left: -20, right: 12 }}><CartesianGrid {...grid} /><XAxis dataKey="name" {...axis} /><YAxis {...axis} allowDecimals={false} /><Tooltip content={<Tip suffix=" démarrage(s)" />} /><Area type="monotone" dataKey="amount" stroke="var(--brand)" strokeWidth={2.5} fill="var(--brand)" fillOpacity=".12" /></AreaChart></ResponsiveContainer></Chart></div> : <Empty />}</>
}
function Directory({ kind, data, onSelect }) {
  const company = kind === 'company', items = groupRows(data, kind, 'count')
  /* One card per entity, unordered and uncapped — the accent bar identifies
     the entity, so this is categorical, not a ramp. */
  const accents = categorical(items.length)
  return <><Intro eyebrow="RÉFÉRENTIEL" title={company ? 'Entreprises' : 'Localisations'} description={company ? 'Vue consolidée des entreprises présentes dans le parc.' : 'Répartition territoriale des logements gérés.'} />{items.length ? <div className="directory">{items.map(({ rows, ...item }, index) => <button key={item.name} onClick={() => onSelect(item.name)}><header><span className={company ? 'company-logo' : 'location-logo'}>{company ? initials(item.name) : <MapPin size={19} />}</span><ChevronRight size={17} /></header><h2>{item.name}</h2><p>{item.amount} logement(s)</p><section><span><b>{sum(rows, 'people')}</b>personnes</span><span><b>{rate(rows)}%</b>occupé</span></section><footer><i style={{ width: `${Math.min(rate(rows), 100)}%`, background: accents[index] }} /></footer></button>)}</div> : <section className="panel"><Empty /></section>}</>
}

function Reports({ data }) {
  /* csvCell quotes and neutralises every field; a remark or a matricule that
     starts with = is text in the export, not a formula the spreadsheet runs. */
  const exportCsv = () => download('rapport-logements-total-work.csv', csvDocument(
    ['Matricule', 'Personnes', 'Capacité', 'Jour de paiement', 'Prix MAD', 'Remarque', 'Responsable', 'Mois de début', 'Entreprise', 'Chantier', 'Localisation'],
    data.map((row) => [row.matricule, row.people ?? '', row.capacity ?? '', row.payDay, row.price, row.remark, row.responsible, row.startMonth, row.company, row.chantier, row.location]),
  ))
  return <><Intro eyebrow="DOCUMENTATION & EXPORT" title="Rapports" description="Préparez une extraction exploitable à partir du périmètre actuellement filtré." /><section className="report"><span><FileBarChart size={27} /></span><div><small>RAPPORT OPÉRATIONNEL</small><h2>État consolidé des logements</h2><p>Ce rapport contient les {data.length} logements correspondant au périmètre courant, avec leurs informations d’occupation et de paiement.</p><section><span><b>{data.length}</b> logements</span><span><b>{sum(data, 'people')}</b> personnes</span><span><b>{money.format(sum(data, 'price'))}</b> montant total</span></section></div><button className="primary" onClick={exportCsv}><Download size={17} />Exporter en CSV</button></section></>
}
function SettingsPage({ theme, setTheme, data, history, currentUser, onImport, onReset }) { return <><Intro eyebrow="CONFIGURATION" title="Paramètres" description="Personnalisez l’affichage et gérez la source locale des données." /><div className="settings"><section className="panel"><header><span><Sun size={19} /></span><div><h2>Apparence de l’interface</h2><p>Sélectionnez le thème adapté à votre environnement de travail.</p></div></header><div className="theme-options"><button className={theme === 'light' ? 'active' : ''} onClick={() => setTheme('light')}><Sun size={18} />Mode clair{theme === 'light' && <Check size={15} />}</button><button className={theme === 'dark' ? 'active' : ''} onClick={() => setTheme('dark')}><Moon size={18} />Mode sombre{theme === 'dark' && <Check size={15} />}</button></div></section></div><SystemHealth /><DataReset currentUser={currentUser} recordCount={data.length} onReset={onReset} /><div id="importation-excel"><ExcelImport records={data} onCommit={onImport} currentUser={currentUser} /></div><ImportHistory history={history} /></> }

function Drawer({ record, close, edit, remove }) {
  const dialog = useRef(null)
  const occupancy = record.capacity ? Math.round(record.people / record.capacity * 100) : null, fields = [['Localisation', record.location, MapPin], ['Entreprise', record.company, BriefcaseBusiness], ['Chantier', record.chantier, Building2], ['Responsable', record.responsible, UserRound], ['Date de paiement', `Le ${String(record.payDay).padStart(2, '0')}`, CalendarDays], ['Mois de début', record.startMonth, CalendarDays]]
  return <Overlay close={close} dialogRef={dialog}><aside className="drawer" ref={dialog}><header><div><span>FICHE DU LOGEMENT</span><h2>{record.matricule}</h2></div><button className="icon" onClick={close}><X size={19} /></button></header><main><div className="drawer-status"><div><span className="unit big"><Building2 size={21} /></span><section><b>Logement {record.matricule}</b><small>{record.location || 'Localisation non renseignée'}</small></section></div><Status item={record} /></div><div className="drawer-kpis"><article><UsersRound size={18} /><span>Personnes</span><b>{record.people ?? '—'}</b></article><article><Gauge size={18} /><span>Capacité</span><b>{record.capacity ?? '—'}</b></article><article><Activity size={18} /><span>Occupation</span><b>{occupancy == null ? '—' : `${occupancy}%`}</b></article></div><h3>Informations générales</h3><div className="drawer-fields">{fields.map(([label, value, Icon]) => <div key={label}><Icon size={16} /><span>{label}</span><b>{value || UNSET}</b></div>)}</div><div className="price"><section><span>Montant mensuel</span><b>{money.format(record.price || 0)}</b></section><CircleDollarSign size={24} /></div><h3>Remarque</h3><p className="remark">{record.remark || 'Aucune remarque renseignée pour ce logement.'}</p></main>{edit && remove && <footer><button className="secondary danger" onClick={remove}><Trash2 size={16} />Supprimer</button><button className="primary" onClick={edit}><Pencil size={16} />Modifier</button></footer>}</aside></Overlay>
}

function Form({ initial, mode, records, close, save }) {
  const [values, setValues] = useState(initial), [errors, setErrors] = useState({}), dialog = useRef(null)
  const update = (key, value) => setValues((current) => ({ ...current, [key]: value }))
  const normalizedInput = normalizeMatricule(values.matricule)
  const originalKey = mode === 'edit' ? recordKey(initial) : ''
  const duplicate = Boolean(normalizedInput) && records.some((row) => recordKey(row) === normalizedInput && recordKey(row) !== originalKey)
  const submit = (event) => { event.preventDefault(); const next = {}, candidate = { ...values, matricule: normalizedInput, payDay: Number(values.payDay) }; if (!candidate.matricule) next.matricule = 'Le matricule est obligatoire.'; else if (duplicate) next.matricule = 'Ce matricule existe déjà dans le système.'; ['people', 'capacity', 'price'].forEach((key) => { if (values[key] === '' || Number(values[key]) < 0) next[key] = 'Saisissez une valeur numérique valide.' }); if (!values.payDay || values.payDay < 1 || values.payDay > 31) next.payDay = 'Le jour doit être compris entre 1 et 31.'; if (Number(values.people) > Number(values.capacity)) next.people = 'Le nombre dépasse la capacité.'; if (!values.location.trim()) next.location = 'La localisation est obligatoire.'; if (!values.company.trim()) next.company = 'L’entreprise est obligatoire.'; if (Object.keys(next).length) return setErrors(next); save({ ...candidate, people: Number(values.people), capacity: Number(values.capacity), price: Number(values.price) }, originalKey || null) }
  const field = (key, label, type = 'text', placeholder = '') => { const message = key === 'matricule' && duplicate ? 'Ce matricule existe déjà dans le système.' : errors[key]; return <label className={message ? 'invalid' : ''}><span>{label}{['matricule', 'people', 'capacity', 'payDay', 'price', 'company', 'location'].includes(key) ? ' *' : ''}</span><input type={type} value={values[key] ?? ''} placeholder={placeholder} onChange={(e) => { update(key, e.target.value); if (errors[key]) setErrors((current) => ({ ...current, [key]: '' })) }} />{message && <small>{message}</small>}</label> }
  return <Overlay close={close} dialogRef={dialog}><form className="form-modal" ref={dialog} onSubmit={submit}><header><div><span>{mode === 'edit' ? 'MISE À JOUR' : 'NOUVEAU LOGEMENT'}</span><h2>{mode === 'edit' ? `Modifier ${initial.matricule}` : 'Ajouter un logement'}</h2><p>Renseignez les informations opérationnelles du logement.</p></div><button type="button" className="icon" onClick={close}><X size={19} /></button></header><main><section><h3>Identification</h3><div className="form-grid">{field('matricule', 'Matricule', 'text', 'TOT-A000')}{field('company', 'Entreprise', 'text', 'Ex. MCA')}{field('location', 'Localisation', 'text', 'Ex. Marrakech')}{field('chantier', 'Chantier', 'text', 'Nom du chantier')}{field('responsible', 'Responsable', 'text', 'Nom du responsable')}</div></section><section><h3>Occupation & paiement</h3><div className="form-grid">{field('people', 'Nombre de personnes', 'number', '0')}{field('capacity', 'Capacité', 'number', '0')}{field('payDay', 'Jour de paiement', 'number', '1 à 31')}{field('price', 'Prix mensuel (MAD)', 'number', '0')}{field('startMonth', 'Mois de début', 'text', 'Ex. juin 2026')}</div></section><section><h3>Informations complémentaires</h3><label><span>Remarque</span><textarea value={values.remark || ''} onChange={(e) => update('remark', e.target.value)} placeholder="Ajouter une remarque utile..." /></label></section></main><footer><button type="button" className="secondary" onClick={close}>Annuler</button><button className="primary" disabled={duplicate}><Check size={16} />{mode === 'edit' ? 'Enregistrer les modifications' : 'Ajouter le logement'}</button></footer></form></Overlay>
}
