import { useState } from 'react'
import { Eye, EyeOff, LockKeyhole, Mail, ShieldCheck } from 'lucide-react'
import logo from '../../TOTAL WORK LOGO.jpg'
import { api } from './api.js'
import './Auth.css'

export function Login({ onLogin, theme, setTheme }) {
  const [email, setEmail] = useState(''), [password, setPassword] = useState(''), [show, setShow] = useState(false), [error, setError] = useState(''), [busy, setBusy] = useState(false), [help, setHelp] = useState(false)
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { await onLogin(await api.login(email, password)) } catch (reason) { setError(reason.message) } finally { setBusy(false) } }
  return <div className="auth-shell"><div className="auth-top"><button className="icon" onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')}>{theme === 'light' ? '☾' : '☀'}</button></div><main className="login-card"><div className="auth-brand"><img src={logo} alt="TOTAL WORK" /><span><b>TOTAL WORK</b><small>Housing Management System</small></span></div><div className="auth-heading"><span>ESPACE SÉCURISÉ</span><h1>Bienvenue</h1><p>Connectez-vous pour accéder à votre espace de gestion.</p></div><form onSubmit={submit}><label><span>Identifiant / Email</span><div><Mail size={16} /><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} autoComplete="username" required /></div></label><label><span>Mot de passe</span><div><LockKeyhole size={16} /><input type={show ? 'text' : 'password'} value={password} onChange={(e) => setPassword(e.target.value)} autoComplete="current-password" required /><button type="button" onClick={() => setShow(!show)} aria-label={show ? 'Masquer le mot de passe' : 'Afficher le mot de passe'}>{show ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label>{error && <p className="auth-error">{error}</p>}{help && <p className="auth-help">Contactez le Founder pour réinitialiser votre mot de passe.</p>}<button className="primary auth-submit" disabled={busy}>{busy ? 'Connexion...' : 'Se connecter'}</button></form><button className="forgot" type="button" onClick={() => setHelp(!help)}>Mot de passe oublié ?</button><footer><ShieldCheck size={14} /> Connexion protégée par TOTAL WORK</footer></main></div>
}
export function AuthLoading() { return <div className="auth-loading"><img src={logo} alt="TOTAL WORK" /><b>Vérification de la session...</b></div> }

export function ForcePasswordChange({ onComplete }) {
  const [values,setValues]=useState({password:'',confirmation:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const submit=async(event)=>{event.preventDefault();setBusy(true);setError('');try{const result=await api.completePasswordReset(values.password,values.confirmation);onComplete(result.user)}catch(reason){setError(reason.message)}finally{setBusy(false)}}
  return <div className="auth-shell password-gate"><main className="login-card"><div className="auth-brand"><img src={logo} alt="TOTAL WORK"/><span><b>TOTAL WORK</b><small>Housing Management System</small></span></div><div className="auth-heading"><span>SÉCURITÉ DU COMPTE</span><h1>Créer votre nouveau mot de passe</h1><p>Votre mot de passe temporaire doit être remplacé avant d’accéder au dashboard.</p></div><form onSubmit={submit}><label><span>Nouveau mot de passe</span><div><LockKeyhole size={16}/><input type="password" minLength="12" value={values.password} onChange={(e)=>setValues({...values,password:e.target.value})} required/></div></label><label><span>Confirmer le mot de passe</span><div><ShieldCheck size={16}/><input type="password" minLength="12" value={values.confirmation} onChange={(e)=>setValues({...values,confirmation:e.target.value})} required/></div></label>{error&&<p className="auth-error">{error}</p>}<button className="primary auth-submit" disabled={busy}>{busy?'Enregistrement...':'Enregistrer'}</button></form></main></div>
}
